### ISSUE TITLE
Fresh clone fail to execute

### ISSUE THREAD

**Issue by Yfeng-44** [tekdogan/gcn#3]
Problem: 
 cuBLAS yield '''CUBLAS_STATUS_NOT_INITIALIZED''' or '''CUBLAS_STATUS_EXECUTION_FAILED'''

Reproduce:
1. git clone
2. cd gsuite && cd cuda
3. make
4. ./cudaDataLoader.o 3

_Originally posted by @Yfeng-44 in https://github.com/tekdogan/gsuite/issues/2#issuecomment-1600791082_

**Comment by tekdogan** [comment]
Hi @Yfeng-44 ,

Did you set your library paths? In my case, it was:

```
export PATH=/okyanus/progs/cuda/cuda-10.1/bin:$PATH
export CPATH=/okyanus/progs/cuda/cuda-10.1/include:$CPATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH/okyanus/progs/cuda/cuda-10.1/lib64/
```

If it is set, can you give it a try with cuBLAS and CUDA versions 8.0?

Best,
Taha

**Comment by Yfeng-44** [comment]
Hi @tekdogan ,

I've tried with CUDA(and cublas) version 10.1, 10.2, 11.0, and 8.0 (in this case, gcc version is 4.8). All of them fails with `./cudaDataLoader.o 3` .

Other models, and dataset works fine, though.

Yuan

**Comment by tekdogan** [comment]
Hi @Yfeng-44 ,

Sorry for the late response. However, I could not reach the dev machine, and I do not have an NVIDIA GPU in my local working environment. As soon as I reproduce the error, I will be updating the repo.

Thanks for the feedback.

Best,
Taha
